### ISSUE TITLE
ssm lookup only works with current region.

### ISSUE THREAD

**Issue by jameszh** [BWITS/ssm_parameter_store#2]
This "show" option is better than lookup, as lookup only works with the current region.

**Comment by ozbillwang** [comment]
Thanks for raising this issue.

Show option has been removed because the reviewer @willthames in PR (https://github.com/ansible/ansible/pull/23460) asked for.  

I am going to support region in lookup. There was a discussion about it, please take a look.

https://github.com/ansible/ansible/pull/23460#discussion_r112187576

If you think that's the right way, I will work on the codes.

**Comment by ozbillwang** [comment]
Another thinking is, 

needn't maintain lookup anymore, restore show option back.  The discussion is here: https://github.com/ansible/ansible/pull/23460#discussion_r112570300

Which way do you prefer?

**Comment by jameszh** [comment]
show option is better, or called “get", more aligned with the api, another option is similar to route53 module, use command(put, get, delete),  instead of state … any of these is  better option than lookup, as lookup occurs at local.

J

**Comment by ozbillwang** [comment]
using show (get) option, you need two tasks

```
- name: Retrieving plain-text secret with custom kms key
   ssm_parameter_store:
     name: "Hello"
     key_id: "aws/ssm"
     state: show
   register: result

- debug: value={{ result }}
```

with lookup, only one. That's the original reason I write this ssm lookup. I think `ssm lookup` still works in some ways.

**Comment by jameszh** [comment]
if possible keep both, when using default region or run at local, lookup is convenient.

**Comment by ozbillwang** [comment]
@jameszh 

### Update:

No parameter such as `region`, `key_id` can be used for boto3 get_parameters(). So that means we can only lookup ssm parameter store in the current region currently. 

`fatal: [localhost]: FAILED! => {"failed": true, "msg": "An unhandled exception occurred while running the lookup plugin 'ssm'. Error was a <class 'botocore.exceptions.ParamValidationError'>, original message: Parameter validation failed:\nUnknown parameter in input: \"region\", must be one of: Names, WithDecryption"}`

Unless boto3 [get_parameter()](http://boto3.readthedocs.io/en/latest/reference/services/ssm.html#SSM.Client.get_parameters) supports region, key_id, and other paramerts.

**Comment by ozbillwang** [comment]
I find a way to lookup ssm key in nominated region

    client = boto3.client('ssm', region_name='us-east-1')

http://russell.ballestrini.net/setting-region-programmatically-in-boto3/

When run lookup get_parameter(), aws api is smart to try all kms keys to encrypt the key, so no need input the kms `key_id` to lookup

I set `WithDecryption` as `true` always, because it makes sense.

**Comment by ozbillwang** [comment]
@jameszh 

I have updated the lookup, it supports region now.

```
- name: lookup ssm parameter store in the current region
  debug: msg="{{ lookup('ssm', 'Hello' ) }}"

- name: lookup a key which doesn't exist
  debug: msg="{{ lookup('ssm', 'NoKey') }}"

- name: lookup a key with key/value pair
  debug: msg="{{ lookup('ssm', 'key=Hello' ) }}"

- name: lookup ssm parameter store in nominated region
  debug: msg="{{ lookup('ssm', 'key=Hello region=us-east-2' ) }}"

- name: lookup ssm parameter store in nominated region, the key doesn't exist
  debug: msg="{{ lookup('ssm', 'key=Hello region=us-east-1' ) }}"
```

**Comment by ozbillwang** [comment]
promoted release to `v1.1.0`

**Comment by ozbillwang** [comment]
https://github.com/boto/boto3/issues/1075
